import type { EditorialProfile } from "./editorial-profiles";

function profile(context: string, href: string, implementation: string, packageName?: string): EditorialProfile {
  return {
    visual: { heading: `Accessible foundations for ${context}`, palette: [{ name: "Primary", value: "#2563EB" }, { name: "Text", value: "#1F2937" }, { name: "Canvas", value: "#FFFFFF" }, { name: "Action", value: "#2563EB" }], typeface: "System UI", typeNote: "Clear, adaptable typography supports readable product and service tasks.", density: "Practical and responsive", densityNote: "Reusable components and guidance keep common interactions consistent." },
    components: ["Button", "Form controls", "Modal", "Table"].map((name) => ({ name, tag: name === "Table" ? "Data" : "Core UI", note: `A reusable ${name.toLowerCase()} foundation for ${context}.`, href })),
    patterns: ["Accessible delivery", "Responsive composition", "Shared foundations"].map((name) => ({ name, useWhen: `Teams build ${context}.`, learn: "How shared components reduce visual and interaction drift.", href })),
    audience: { design: { title: `Design ${context}`, description: "Use the shared component and guidance baseline to create coherent experiences.", facts: [["Context", context], ["Accessibility", "Core focus"], ["Foundation", implementation], ["Delivery", "Reusable components"]], links: [{ label: "System documentation", href }] }, developer: { title: `Build ${context}`, description: "Use the existing implementation rather than recreating common interface behavior.", facts: [["Implementation", implementation], ["Package", packageName ?? "Project resources"], ["Accessibility", "Supported"], ["Adoption", "Incremental"]], links: [{ label: "System documentation", href }], packageName } },
    decision: { choose: `You are building ${context} and need its established accessible component foundation.`, reconsider: "You need a system for a different product, platform, or visual context." },
  };
}

export const NEXT_EDITORIAL_PROFILES: Record<string, EditorialProfile> = {
  "bold-bridge-design-system": profile("Brazilian public services", "https://bold.bridge.ufsc.br/", "React", "bold-ui"),
  "jb-design-system": profile("framework-agnostic web products", "https://javadbat.github.io/design-system", "Web Components", "jb-core"),
  materializecss: profile("responsive Material-style websites", "https://materializecss.com/", "HTML, Sass, CSS, and JavaScript", "@materializecss/materialize"),
  "w3c-design-system": profile("W3C standards and documentation websites", "https://design-system.w3.org/", "HTML, Sass, CSS, JavaScript, and Twig"),
  "lemon-squeezy-wedges": profile("commerce and software products", "https://www.lemonsqueezy.com/wedges/docs/", "React and Tailwind CSS", "@lemonsqueezy/wedges"),
  "vtex-styleguide": profile("VTEX commerce administration", "https://styleguide.vtex.com/", "React and Tachyons", "@vtex/styleguide"),
  "decentraland-ui": profile("Decentraland marketplace and wallet interfaces", "https://ui.decentraland.org/", "React", "decentraland-ui"),
  "bbc-gel-global-experience-language": profile("BBC-aligned inclusive web patterns", "https://bbc.github.io/gel/", "HTML, CSS, and JavaScript"),
  "amplify-ui": profile("AWS Amplify-connected product interfaces", "https://ui.docs.amplify.aws/", "React, Vue, and Angular", "@aws-amplify/ui-react"),
  "alaska-airlines": profile("Alaska Airlines digital experiences", "https://auro.alaskaair.com/", "Web Components"),
  "korea-design-system": profile("South Korean government digital public services", "https://www.krds.go.kr", "HTML, CSS, and JavaScript"),
  "british-gas-nucleus": profile("British Gas customer and product experiences", "https://britishgas.design/", "Web Components"),
  jobber: profile("service-business software", "https://atlantis.getjobber.com", "React and React Native", "@jobber/components"),
  "astro-uxds": profile("space-focused digital products", "https://astrouxds.com/", "Stencil Web Components", "@astrouxds/astro-web-components"),
  nordhealth: profile("healthcare digital products", "https://nordhealth.design/", "Web Components, React, and Vue", "@nordhealth/components"),
  "artsy-palette": profile("Artsy marketplace and editorial experiences", "https://palette.artsy.net/", "React", "@artsy/palette"),
  "pluralsight-design-system": profile("digital learning products", "https://design-system.pluralsight.com/", "React and TypeScript"),
  "engie-fluid-design-system": profile("ENGIE digital experiences", "https://www.engie.design", "Web Components, React, and Angular", "@engie-group/fluid-design-system-react"),
  foundation: profile("responsive websites and products", "https://get.foundation/", "HTML, Sass, CSS, and JavaScript", "foundation-sites"),
  "privy-persona-design-system": profile("privacy-focused commerce products", "https://privy-open-source.github.io/design-system/", "React and TypeScript"),
  "city-of-boston-fleet": profile("Boston public digital services", "https://patterns.boston.gov/", "HTML, CSS, and JavaScript"),
  "sage-by-kajabi": profile("creator-commerce products", "https://sage.kajabi.com", "React and Ruby", "@kajabi/sage-react"),
  "autoguru-overdrive": profile("automotive service and marketplace products", "http://overdrive.autoguru.io/", "React, TypeScript, and Vanilla Extract", "@autoguru/overdrive"),
  reshaped: profile("themeable responsive React products", "https://reshaped.so", "React", "reshaped"),
  "wmca-design-system": profile("West Midlands regional public services", "https://designsystem.wmca.org.uk/", "Nunjucks, Sass, JavaScript, and HTML"),
  "decathlon-design-system-vitamin": profile("Decathlon cross-platform product experiences", "https://decathlon.design/", "Web Components, React, and Vue", "@vtmn/web-components"),
  duet: profile("accessible public and product interfaces", "https://www.duetds.com", "Web Components, React, Angular, and Vue", "@duetds/components"),
  "intuit-harmony": profile("QuickBooks financial product experiences", "https://designsystem.quickbooks.com/", "React"),
  "oracle-redwood": profile("Oracle enterprise applications", "https://redwood.oracle.com", "Oracle JET, React, iOS, and Android"),
  seeds: profile("Sprout Social product experiences", "https://sproutsocial.com/seeds", "React"),
  "co-op-experience-library": profile("Co-op customer and service experiences", "https://www.coop.co.uk/experience-library/", "HTML and CSS", "@coopdigital/foundations"),
  "orange-unified-design-system": profile("Orange web and native products", "https://unified-design-system.orange.com/", "HTML, Sass, CSS, JavaScript, Android, iOS, and Flutter", "@ouds/web-orange"),
  thumbprint: profile("Thumbtack marketplace experiences", "https://thumbprint.design/", "React and Sass", "@thumbtack/thumbprint-react"),
  "sap-fiori": profile("SAP role-based enterprise applications", "https://experience.sap.com/fiori-design/", "SAPUI5, Web Components, iOS, and Android"),
  "apple-developer-design-guidelines": profile("Apple platform experiences", "https://developer.apple.com/design/", "iOS, iPadOS, macOS, watchOS, tvOS, and visionOS"),
  "mesh-design-system": profile("nib multi-brand digital products", "https://www.meshdesignsystem.com/", "React, CSS, and Tailwind CSS", "@nib-group/mesh-theme"),
  "aurora-government-of-canada": profile("Government of Canada digital services", "https://design.gccollab.ca/", "React, HTML, and CSS"),
  "ray-by-wework": profile("WeWork web properties", "https://ray.wework.com", "HTML, Sass, and JavaScript", "@wework/ray-core"),
  "ebay-evo": profile("eBay product and brand experiences", "https://playbook.ebay.com/design-system", "CSS, Marko, React, and Native"),
  "firefox-photon-design-system": profile("Firefox browser interfaces", "https://firefox-source-docs.mozilla.org/toolkit/themes/shared/design-system/docs/README.design-tokens.stories.html", "Firefox design tokens and shared components"),
  vercel: profile("Vercel developer experiences", "https://vercel.com/geist", "React and Next.js"),
  "visa-product-design-system": profile("Visa payment experiences", "https://design.visa.com/", "React, Angular, Flutter, HTML, and CSS"),
  uiverse: profile("community HTML and CSS interface examples", "https://uiverse.io", "HTML and CSS"),
  "hudl-design-system": profile("Hudl sports product experiences", "https://uniform.hudl.com/", "React, HTML, Sass, and JavaScript"),
  "dell-design-system": profile("Dell digital product experiences", "https://www.delldesignsystem.com/", "Token-led foundations and components"),
  "adjust-atlas": profile("Adjust product-suite experiences", "https://atlas.adeven.com", "React, Sass, and JavaScript"),
  "hubspot-canvas": profile("HubSpot product and brand experiences", "https://canvas.hubspot.com/", "Interface foundations and patterns"),
  ratio: profile("Rambler digital products", "https://ui-kit.rambler.ru/", "React", "rambler-ui"),
  "enigma-boundless": profile("themeable React application interfaces", "https://boundless.js.org/", "React", "boundless"),
  "vue-design-system": profile("Vue design-system documentation workflows", "https://vueds.com/", "Vue and Sass"),
  cloudflare: profile("Cloudflare web dashboard interfaces", "https://cloudflare.github.io/cf-ui/", "React"),
  "mixpanel-design-system": profile("Mixpanel analytics workflows", "https://design.mixpanel.com", "React"),
  "mail-ru-group-paradigm": profile("Mail.ru Group digital product experiences", "https://design.mail.ru/", "Visual language and interface components"),
  "morningstar-design-system": profile("Morningstar financial products", "http://designsystem.morningstar.com/", "React"),
  "bolt-design-system": profile("application and Drupal content experiences", "https://boltdesignsystem.com/", "React, Twig, and Web Components"),
  "michelin-motion": profile("Michelin cross-platform applications", "https://designsystem.michelin.com/", "Angular and Svelte"),
  "aragon-ui": profile("Aragon ecosystem interfaces", "https://www.aragon.org/", "React"),
  "at-uikit": profile("Vue web interfaces", "https://at-ui.github.io/at-ui/#/en", "Vue 2", "at-ui"),
  "futurelearn-pattern-library": profile("FutureLearn learning journeys", "https://www.futurelearn.com/pattern-library", "Inclusive learning patterns and responsive product UI"),
  "samsung-design-system": profile("Samsung cross-device experiences", "https://developer.samsung.com/design-system", "Cross-device design guidance"),
  "yelp-styleguide": profile("Yelp marketplace products", "https://www.yelp.com/styleguide", "HTML, Sass, iOS, and Android"),
  "brand-estonia": profile("Estonia national digital expression", "https://brand.estonia.ee", "National identity guidance and reusable assets"),
  "persona-design-system": profile("Persona identity-verification experiences", "https://design.withpersona.com/", "Product foundations and reusable components"),
  "datadog-druids": profile("Datadog observability interfaces", "https://druids.datadoghq.com/", "React and CSS"),
  "aalto-university": profile("Aalto University digital services", "https://brand.aalto.fi/", "React, HTML, and CSS"),
  "buzzvil-design-system": profile("Buzzvil multi-market product experiences", "https://design.buzzvil.com/", "Flexible brand and interaction guidance"),
  enel: profile("Enel X energy products and digital services", "https://dsyui.enelx.com/", "Branded UI guidance and reusable components"),
  "nationbuilder-radius": profile("NationBuilder organizing and campaign tools", "https://www.nationbuilder.design/", "React"),
  duolingo: profile("Duolingo global brand experiences", "https://design.duolingo.com/", "Voice, visual identity, and illustration guidance"),
  "heroku-purple3": profile("Heroku developer-platform products", "https://design.herokai.com/", "Interface foundations and patterns"),
  "louder-than-ten-manual": profile("Louder Than Ten client-service work", "https://www.louderthanten.com/manual", "HTML, CSS, and practical agency standards"),
  "teambition-clarity-design": profile("Teambition collaboration software", "https://design.teambition.com/", "Visual foundations, components, and workflow patterns"),
  "goodbarber-design-system": profile("GoodBarber native and progressive web apps", "https://www.goodbarber.com/uxdesign/", "iOS, Android, and Progressive Web Apps"),
  "marvel-styleguide": profile("Marvel collaborative design platform", "https://marvelapp.com/styleguide", "Interface foundations and reusable patterns"),
  "monzo-tone-of-voice": profile("Monzo financial communication", "https://monzo.com/tone-of-voice/", "Inclusive writing principles and trust-building content"),
};
