import {
  siAndroid, siAngular, siApple, siAriakit, siBootstrap, siCss, siEmberdotjs,
  siFlutter, siHtml5, siJavascript, siJetpackcompose, siLess, siMarko,
  siNextdotjs, siNunjucks, siPwa, siReact, siRuby, siSap, siSass,
  siStyledcomponents, siSvelte, siTailwindcss, siTypescript,
  siUber, siVanillaextract, siVuedotjs, siWebcomponentsdotorg,
  type SimpleIcon,
} from "simple-icons";

export type GenericTechnologyIcon = "boxes" | "database" | "gauge" | "leaf" | "monitor" | "smartphone";
export type TechnologyIconDefinition = SimpleIcon | GenericTechnologyIcon | { src: string };

export const TECHNOLOGY_ICONS: Record<string, TechnologyIconDefinition> = {
  Android: siAndroid,
  Angular: siAngular,
  Ariakit: siAriakit,
  Bootstrap: siBootstrap,
  CSS: siCss,
  Ember: siEmberdotjs,
  Flutter: siFlutter,
  Grommet: "boxes",
  HTML: siHtml5,
  iOS: siApple,
  iPadOS: siApple,
  JavaScript: siJavascript,
  "Jetpack Compose": siJetpackcompose,
  Less: siLess,
  "Lightning Web Components": { src: "/system-logos/salesforce.svg" },
  macOS: siApple,
  Marko: siMarko,
  Native: "smartphone",
  "Next.js": siNextdotjs,
  Nunjucks: siNunjucks,
  OpenUI5: siSap,
  "Oracle JET": "database",
  "Progressive Web App": siPwa,
  React: siReact,
  "React Aria": siReact,
  "React Native": siReact,
  Ruby: siRuby,
  SAPUI5: siSap,
  Sass: siSass,
  "styled-components": siStyledcomponents,
  Styletron: siUber,
  Svelte: siSvelte,
  Tachyons: "gauge",
  "Tailwind CSS": siTailwindcss,
  tvOS: siApple,
  Twig: "leaf",
  TypeScript: siTypescript,
  "Vanilla Extract": siVanillaextract,
  visionOS: siApple,
  Vue: siVuedotjs,
  watchOS: siApple,
  "Web Components": siWebcomponentsdotorg,
  Windows: "monitor",
};
