import assert from "node:assert/strict";
import { getCatalog } from "../lib/catalog";
import { matchesFilters, searchSystems, sortSystems, suggestSystems, type CatalogFilters } from "../lib/catalog-filters";
import { TECHNOLOGY_ICONS } from "../lib/technology-icons";
import { EDITORIAL_PROFILES } from "../lib/editorial-profiles";

const systems = getCatalog();
const technologies = new Set(systems.flatMap((system) => system.frameworks));
const filters: CatalogFilters = { query: "", resources: ["figma"], technology: ["React"], guidance: ["accessibility"], bestFor: ["enterprise"], sort: "recommended" };

assert.equal(matchesFilters(systems.find((system) => system.id === "carbon")!, filters), true);
assert.equal(sortSystems(systems, "name")[0].name, [...systems].sort((a, b) => a.name.localeCompare(b.name))[0].name);
const recommended = sortSystems(systems, "recommended");
assert.ok(systems.every((system) => system.recommendation_score >= 0 && system.recommendation_score <= 100));
assert.ok(recommended.every((system, index) => index === 0 || recommended[index - 1].recommendation_score >= system.recommendation_score));
assert.equal(suggestSystems(systems, "shopify")[0]?.name, "Polaris");
assert.deepEqual(searchSystems(systems, "motion").map((system) => system.name), ["Motion"]);
assert.deepEqual(searchSystems(systems, "montion").map((system) => system.name), ["Motion"]);
assert.deepEqual(searchSystems(systems, "moton").map((system) => system.name), ["Motion"]);
assert.deepEqual(searchSystems(systems, "motion design system").map((system) => system.name), ["Motion"]);
assert.equal(searchSystems(systems, "carbn")[0]?.name, "Carbon Design System");
assert.equal(searchSystems(systems, "polris")[0]?.name, "Polaris");
assert.equal(searchSystems(systems, "shopyfy")[0]?.name, "Polaris");
assert.equal(searchSystems(systems, "atlassain")[0]?.name, "Atlassian Design System");
assert.equal(searchSystems(systems, "material desgin system")[0]?.name, "Material Design");
assert.equal(searchSystems(systems, "nice desgin sytem")[0]?.name, "NICE Design System");
assert.equal(searchSystems(systems, "cloudscpe")[0]?.name, "Cloudscape");
assert.deepEqual(searchSystems(systems, "patern").map((system) => system.name).sort(), ["FutureLearn Pattern Library", "PatternFly"]);
assert.equal(suggestSystems(systems, "", 3).length, 3);
assert.deepEqual([...technologies].filter((technology) => !TECHNOLOGY_ICONS[technology]), []);
assert.equal(Object.keys(EDITORIAL_PROFILES).length, 15);
assert.deepEqual(Object.keys(EDITORIAL_PROFILES).filter((id) => !systems.some((system) => system.id === id)), []);
assert.equal(systems.some((system) => system.name === "Audi UI Kit"), false);
assert.equal(systems.filter((system) => system.github_repo === "microsoft/fluentui").length, 1);
assert.equal(systems.find((system) => system.github_repo === "microsoft/fluentui")?.name, "Fluent UI");
assert.equal(systems.find((system) => system.github_repo === "microsoft/fluentui")?.site_url, "https://fluent2.microsoft.design/");
assert.equal(systems.find((system) => system.company === "Shopify")?.name, "Polaris");
assert.equal(systems.find((system) => system.company === "GitHub")?.name, "Primer");
assert.equal(systems.find((system) => system.company === "GitLab")?.name, "Pajamas");
assert.equal(systems.find((system) => system.company === "Amazon Web Services" && system.id === "aws-cloudscape-design-system")?.name, "Cloudscape");
assert.equal(systems.find((system) => system.id === "intuit-harmony")?.name, "QuickBooks");
assert.equal(systems.find((system) => system.id === "jobber")?.name, "Atlantis");
assert.equal(systems.find((system) => system.id === "firefox-photon-design-system")?.name, "Acorn");
assert.equal(systems.find((system) => system.id === "pluralsight-design-system")?.name, "Pando");
assert.equal(systems.find((system) => system.id === "co-op-experience-library")?.name, "Coop");
assert.equal(systems.find((system) => system.id === "vercel")?.name, "Geist");
assert.equal(systems.find((system) => system.id === "sap-openui")?.name, "OpenUI5");
assert.equal(systems.find((system) => system.id === "hpe-design-system")?.name, "HPE");
assert.equal(systems.find((system) => system.id === "hpe-design-system")?.company, "Hewlett Packard Enterprise");
assert.equal(systems.find((system) => system.id === "ebay-evo")?.name, "Evo");
assert.equal(systems.find((system) => system.id === "ebay-evo")?.site_url, "https://playbook.ebay.com/design-system");
assert.equal(systems.find((system) => system.id === "foundation")?.name, "Foundation Framework");
assert.equal(systems.find((system) => system.id === "materializecss")?.name, "MaterializeCSS");
assert.equal(systems.find((system) => system.id === "brand-estonia")?.name, "Brand Estonia");
assert.equal(systems.find((system) => system.id === "aragon-ui")?.site_url, "https://www.aragon.org/");
assert.equal(systems.filter((system) => system.name === "Persona").length, 2);
assert.equal(systems.find((system) => system.id === "privy-persona-design-system")?.company, "Privy");
assert.equal(systems.find((system) => system.id === "persona-design-system")?.company, "Persona Identities");
assert.equal(systems.some((system) => system.id === "financial-times-origami"), false);
assert.equal(systems.some((system) => system.id === "ibm-design-language"), false);
assert.equal(systems.some((system) => system.id === "bumbag-ui"), false);
assert.equal(systems.some((system) => system.id === "tizen-circularui"), false);
assert.equal(systems.find((system) => system.id === "samsung-design-system")?.site_url, "https://developer.samsung.com/design-system");
assert.equal(systems.find((system) => system.id === "wmca-design-system")?.name, "WMCA");
assert.equal(systems.find((system) => system.id === "wmca-design-system")?.company, "West Midlands Combined Authority");
assert.equal(systems.find((system) => system.id === "wmca-design-system")?.github_repo, "wmcadigital/wmca-design-system");
assert.equal(systems.some((system) => system.company === "NASA"), false);
assert.equal(systems.some((system) => system.company === "CBRE"), false);
assert.equal(systems.some((system) => system.company === "Nordnet"), false);
assert.equal(systems.some((system) => system.company === "CA Technologies"), false);
assert.equal(systems.filter((system) => system.company === "SEEK").length, 1);
assert.equal(systems.find((system) => system.company === "SEEK")?.name, "Braid Design System");
assert.equal(systems.some((system) => system.company === "BuzzFeed"), false);
assert.equal(systems.some((system) => system.company === "Blip"), false);
assert.equal(systems.some((system) => system.company === "Buildit"), false);
assert.equal(systems.some((system) => system.company === "Pusher"), false);
assert.equal(systems.some((system) => system.company === "Foyer"), false);
assert.equal(systems.some((system) => system.company === "Help Scout"), false);
assert.equal(systems.some((system) => system.company === "Uswitch"), false);
assert.equal(systems.some((system) => system.company === "Latitude Financial Services"), false);
assert.equal(systems.some((system) => system.company === "Pivotal"), false);
assert.equal(systems.some((system) => system.company === "Appear Here"), false);
assert.equal(systems.some((system) => system.company === "Finland Promotion Board"), false);
assert.equal(systems.some((system) => system.company === "Mailchimp"), false);
assert.equal(systems.some((system) => system.company === "Starbucks"), false);
assert.equal(systems.find((system) => system.company === "Rambler")?.name, "Ratio");
assert.equal(systems.find((system) => system.company === "Rambler")?.site_url, "https://ui-kit.rambler.ru/");
assert.equal(systems.find((system) => system.company === "Rambler")?.github_repo, "rambler-digital-solutions/rambler-ui");
assert.equal(systems.some((system) => ["rendition", "wix-style-react"].includes(system.id)), false);
assert.equal(systems.find((system) => system.id === "autoguru-overdrive")?.github_repo, "autoguru-au/overdrive");
assert.equal(systems.some((system) => system.github_repo === "eBay/skin"), false);
assert.equal(systems.some((system) => system.github_repo === "grommet/grommet"), false);
assert.equal(systems.some((system) => system.github_repo === "SAP/fundamental"), false);
assert.equal(systems.some((system) => system.github_repo === "okta/odyssey"), false);
assert.equal(systems.some((system) => system.github_repo === "vimeo/iris"), false);
assert.equal(systems.find((system) => system.company === "Decathlon")?.name, "Vitamin");
assert.equal(systems.find((system) => system.id === "dell-design-system")?.name, "DDS");
assert.equal(systems.find((system) => system.id === "dell-design-system")?.company, "Dell Technologies");
assert.equal(systems.find((system) => system.id === "dell-design-system")?.site_url, "https://www.delldesignsystem.com/");
assert.equal(systems.find((system) => system.id === "esri-calcite")?.name, "Calcite");
assert.equal(systems.find((system) => system.id === "esri-calcite")?.github_repo, "Esri/calcite-design-system");
assert.equal(systems.find((system) => system.id === "helsinki-design-system")?.company, "City of Helsinki");
assert.equal(systems.find((system) => system.id === "visa-product-design-system")?.name, "VPDS");
assert.equal(systems.find((system) => system.id === "visa-product-design-system")?.site_url, "https://design.visa.com/");
assert.equal(systems.find((system) => system.id === "wikimedia-codex")?.name, "Codex");
assert.equal(systems.find((system) => system.id === "wikimedia-codex")?.company, "Wikimedia Foundation");
assert.equal(systems.find((system) => system.id === "kiwi-com-orbit")?.name, "Orbit");
assert.equal(systems.find((system) => system.id === "kiwi-com-orbit")?.github_repo, "kiwicom/orbit");
assert.equal(systems.find((system) => system.id === "kiwi-com-orbit")?.site_url, "https://kiwicom.github.io/orbit/");
assert.equal(systems.find((system) => system.id === "nsw-design-system")?.company, "NSW Government");
assert.equal(systems.find((system) => system.id === "orange-unified-design-system")?.name, "OUDS");
assert.equal(systems.find((system) => system.id === "patternfly")?.company, "Red Hat");
assert.equal(systems.find((system) => system.id === "patternfly")?.npm_package, "@patternfly/react-core");
assert.equal(systems.find((system) => system.id === "razorpay-blade")?.name, "Blade");
assert.equal(systems.find((system) => system.id === "razorpay-blade")?.github_repo, "razorpay/blade");
assert.equal(systems.find((system) => system.id === "denmark-common-design-system")?.name, "Common Design System");
assert.equal(systems.find((system) => system.id === "denmark-common-design-system")?.site_url, "https://designsystem.dk/");
assert.equal(systems.find((system) => system.id === "inps-sirio")?.name, "Sirio");
assert.equal(systems.find((system) => system.id === "inps-sirio")?.github_repo, "INPS-it/sirio-kit-web");
assert.equal(systems.find((system) => system.id === "scottish-government-design-system")?.github_repo, "scottish-government-design-system/design-system");
assert.equal(systems.find((system) => system.id === "sumup-circuit")?.name, "Circuit");
assert.equal(systems.find((system) => system.id === "sumup-circuit")?.site_url, "https://circuit.sumup.com/");
assert.equal(systems.find((system) => system.id === "w3c-design-system")?.site_url, "https://design-system.w3.org/");
assert.equal(systems.find((system) => system.id === "agriculture-design-system")?.github_repo, "agriculturegovau/agds-next");
assert.equal(systems.find((system) => system.id === "datadog-druids")?.name, "DRUIDS");
assert.equal(systems.find((system) => system.id === "lemon-squeezy-wedges")?.name, "Wedges");
assert.equal(systems.find((system) => system.id === "michelin-motion")?.name, "Motion");
assert.equal(systems.find((system) => system.id === "nice-design-system")?.npm_package, "@nice-digital/design-system");
assert.deepEqual(systems.find((system) => system.id === "aalto-university")?.frameworks, ["React", "HTML", "CSS"]);
assert.equal(systems.find((system) => system.id === "adjust-atlas")?.github_repo, "adjust/atlas");
assert.equal(systems.find((system) => system.id === "bbc-gel-global-experience-language")?.site_url, "https://bbc.github.io/gel/");
assert.equal(systems.find((system) => system.id === "british-gas-nucleus")?.github_repo, "centrica-engineering/nucleus-docs");
